spring:
  # thymeleaf配置
  thymeleaf:
    # 缓存
    cache: false
  # 数据库源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.62.214:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root1024
    hikari:
      # 连接池名称
      pool-name: DataHikariCP
      # 最小空闲连接处
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 最大连接数。默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redi配置
  redis:
    #服务器地址
    host: 134.175.62.214
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    connect-timeout: 10000ms
    image: redis:7
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
#    host: 127.0.0.1


# Mybatis-plus配置
mybatis-plus:
  # 配置 Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.wjj.miaosha.pojo


# Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.wjj.miaosha.mapper: debug

knife4j:
  enable: true

server:
  port: 8080
